# Generated by Django 5.1.6 on 2025-02-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
    ]
