# Generated by Django 5.1.6 on 2025-02-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='situation',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
    ]
