# Generated by Django 5.1.6 on 2025-02-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='situation',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
